title = "Hugo: A Fast and Flexible Website Generator"
baseurl = "http://thingiverse.io/"
MetaDataFormat = "yaml"
pluralizeListTitles = false

[blackfriday]
  plainIDAnchors = true

[params]
  description = "Documentation for thingiverseIO, the new kickass motherfucker in town"
  author = "Joern Weissenborn and friends"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "Download"
    pre = "<i class='fa fa-download'></i>"
    url = "https://github.com/ThingiverseIO/thingiverseIO"
    weight = -200
[[menu.main]]
    name = "About tvIO"
    identifier = "about"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
[[menu.main]]
    name = "Getting Started"
    identifier = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
[[menu.main]]
    name = "Guide"
    identifier = "guide"
    pre = "<i class='fa fa-file-text'></i>"
    weight = -90
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = -40
[[menu.main]]
    name = "Troubleshooting"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-wrench'></i>"
    weight = -30
[[menu.main]]
    name = "Tool"
    url = "/tool/"
    pre = "<i class='fa fa-cogs'></i>"
    weight = -25
